### ISSUE TITLE
網站設計進階 第一週 簽到討論區

### ISSUE THREAD

**Issue by ccckmit** [ccccourse1/ws110a#1]
請寫『姓名：到』！

**Comment by ccckmit** [comment]
https://gitlab.com/ccc110/ws

**Comment by tyiio445** [comment]
王博緯 到!

**Comment by KMC1911** [comment]
陳楷茗 到！

**Comment by jenny126** [comment]
蔡宜潔 到!

**Comment by ukarara** [comment]
蘇祐汝 到

**Comment by zhengyucen** [comment]
鄭宇岑 到

**Comment by shaoan901226** [comment]
黃紹安 到

**Comment by 123AE321** [comment]
巫承勳 到

**Comment by Sakura01210** [comment]
王冠文 到

**Comment by yucing** [comment]
蘇郁晴 到

**Comment by weiian000** [comment]
李維晏 到

**Comment by tony8880221** [comment]
黃偉峯 到

**Comment by weng0418** [comment]
翁瑋泓 到

**Comment by yilong2019** [comment]
張鐿瀧 到

**Comment by OohelloworldoO** [comment]
鄭智陽 到

**Comment by cabdy1735** [comment]
李翊慈 到

**Comment by HongMing0603** [comment]
王鴻銘 到

**Comment by bolinlinlinlin** [comment]
吳博霖 到

**Comment by qwezxca123** [comment]
曾旭宏 到

**Comment by RyanChen-01** [comment]
陳文吉 到

**Comment by ccckmit** [comment]
git clone https://gitlab.com/ccc110/ws.git

```
  501  deno run hello.js
  502  deno run --allow-read read.js
  504  deno run -A read.js
```

**Comment by Bob-1231** [comment]
翁子麒 到

**Comment by ceen123** [comment]
吳鑛山 到

**Comment by victor881212** [comment]
陳宏遠 到

**Comment by ccckmit** [comment]
請進 Google Meet

https://meet.google.com/hqw-jhry-opj

**Comment by Yongsin0** [comment]
陳詠鑫 到

**Comment by cynthia1231** [comment]
張芷榕 到

**Comment by yumao57** [comment]
劉宸羽 到

**Comment by rightmilk** [comment]
施侑儒 到

**Comment by al2698** [comment]
姜呈諭 到

**Comment by derek120432** [comment]
李韋德 到

**Comment by QuiLinxinag** [comment]
邱麟翔 到

**Comment by Kenttsai1** [comment]
蔡宗霖 到

**Comment by z22756392z** [comment]
徐伯元 到

**Comment by stereomp3** [comment]
魏仲彥 到1

**Comment by ccckmit** [comment]
https://gitlab.com/ccc110/ws/-/tree/master/01-basics/callback

**Comment by Paouser** [comment]
劉煒辰 到

**Comment by ccckmit** [comment]
```
(base) csienqu-teacher:callback csienqu$ deno run call.js
hello
(base) csienqu-teacher:callback csienqu$ deno run df.js
df(square, 2) 4.0001000000078335
df(sin(pi/4)) 0.7070714246693033
(base) csienqu-teacher:callback csienqu$ deno run mymap.js
[ 25, 4, 16 ]
```

**Comment by ccckmit** [comment]
```
$ Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

$ choco install deno

```

**Comment by ccckmit** [comment]
> iwr https://deno.land/x/install/install.ps1 -useb | iex

**Comment by ccckmit** [comment]
```
$ pwd
/Users/csienqu/Desktop/ccc/ws/02-http/01-hello

$ deno run -A helloServer.js
http://localhost:8000/
```

**Comment by 4YCAaaa** [comment]
李思慧 到～

**Comment by ccckmit** [comment]
http://www.ruanyifeng.com/blog/2019/09/curl-reference.html

**Comment by ccckmit** [comment]
```
$ curl -I http://www.example.com
HTTP/1.1 200 OK
Accept-Ranges: bytes
Age: 213446
Cache-Control: max-age=604800
Content-Type: text/html; charset=UTF-8
Date: Fri, 17 Sep 2021 02:22:06 GMT
Etag: "3147526947"
Expires: Fri, 24 Sep 2021 02:22:06 GMT
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT
Server: ECS (sab/5695)
X-Cache: HIT
Content-Length: 1256
```

**Comment by ccckmit** [comment]
```
$ deno run -A htmlServer.js
http://localhost:8000/index.html
req.url= /index.html
req.url= /favicon.ico
error= NotFound: No such file or directory (os error 2)
    at processResponse (core.js:224:13)
    at Object.jsonOpAsync (core.js:242:12)
    at async open (deno:cli/rt/30_files.js:44:17)
    at async Object.readTextFile (deno:cli/rt/40_read_file.js:30:18)
    at async file:///Users/csienqu/Desktop/ccc/ws/02-http/02-fileServer/htmlServer.js:7:18
req.url= /hello.html
req.url= /hello.html
req.url= /xxx.html
error= NotFound: No such file or directory (os error 2)
    at processResponse (core.js:224:13)
    at Object.jsonOpAsync (core.js:242:12)
    at async open (deno:cli/rt/30_files.js:44:17)
    at async Object.readTextFile (deno:cli/rt/40_read_file.js:30:18)
    at async file:///Users/csienqu/Desktop/ccc/ws/02-http/02-fileServer/htmlServer.js:7:18
```

**Comment by ccckmit** [comment]
```
$ deno run -A oakHello.js
start at : http://127.0.0.1:8000
```

**Comment by ccckmit** [comment]
```js
app.use((ctx) => {
  ctx.response.body = "Hello World!";
});
```

**Comment by iwantall2333** [comment]
莊汶娟 到
